# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Bernat Ferragut"



author:
  name:             Bernat Ferragut
  github:           bernatferragut
  linkedin:         bernat-ferragut-1972163
  behance:          behance.net/elbernate038
  email:            elbernat@gmail.com

# Google-analytics
google-analytics:
  id:               "UA-116906134-1"

# Disqus
disqus:
  id:               "http://disqus.com/by/bernatferragut"

# URL
#url:               "https://bernatferragut.github.io/vr-blog/" # the base hostname & protocol for your site
url:               "http://bernatferragut.com" # use this url when develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/Montreal
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "Bernat"
    url:            "/bernat"
  - name:           "Recent"
    url:            "/recent"  
  - name:           "Visual"
    url:            "/visual"
  - name:           "Art"
    url:            "https://www.behance.net/elbernate038"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Glitch"
    url:            "https://glitch.com/@bernatferragut"
  - name:           "Github"
    url:            "https://github.com/bernatferragut"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
